# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 173) do

  create_table "calculations", :force => true do |t|
    t.column "string_1",    :string
    t.column "string_2",    :string
    t.column "string_3",    :string
    t.column "string_4",    :string
    t.column "string_5",    :string
    t.column "double_1",    :decimal,  :precision => 8, :scale => 2
    t.column "double_2",    :decimal,  :precision => 8, :scale => 2
    t.column "double_3",    :decimal,  :precision => 8, :scale => 2
    t.column "integer_1",   :integer
    t.column "integer_2",   :integer
    t.column "integer_3",   :integer
    t.column "date_time_1", :datetime
    t.column "date_1",      :date
    t.column "time_1",      :time
  end

  create_table "categories", :force => true do |t|
    t.column "category_name",          :string
    t.column "parent_id",              :integer
    t.column "default_category",       :boolean, :default => false
    t.column "block_code",             :string
    t.column "participant_limit",      :integer
    t.column "number_of_participants", :boolean
    t.column "added_by",               :string
  end

  create_table "ct_class_term_and_conditions", :force => true do |t|
    t.column "ct_class_id",          :integer
    t.column "terms_and_conditions", :text
  end

  create_table "ct_classes", :force => true do |t|
    t.column "term_id",                     :integer
    t.column "class_name",                  :string
    t.column "abbreviation",                :string
    t.column "registration_start",          :datetime
    t.column "registration_end",            :datetime
    t.column "default_roster_maximum",      :integer,                                :default => 99
    t.column "default_price",               :decimal,  :precision => 8, :scale => 2, :default => 0.0
    t.column "default_late_date",           :datetime
    t.column "default_late_fee",            :decimal,  :precision => 8, :scale => 2
    t.column "comment",                     :text
    t.column "class_track_id",              :integer
    t.column "default_early_bird_date",     :datetime
    t.column "default_early_bird_discount", :decimal,  :precision => 8, :scale => 2, :default => 0.0
    t.column "default_payment_due_date",    :datetime
    t.column "default_minimum_age",         :integer
    t.column "default_maximum_age",         :integer,                                :default => 99
  end

  create_table "ct_instructors", :force => true do |t|
    t.column "participant_id", :integer
    t.column "google_account", :string
  end

  create_table "ct_reservations", :force => true do |t|
    t.column "ct_session_schedule_id", :integer
    t.column "session_date",           :date
    t.column "start_time",             :time
    t.column "end_time",               :time
    t.column "playing_area_id",        :integer
  end

  create_table "ct_rosters", :force => true do |t|
    t.column "participant_id",                 :integer
    t.column "ct_session_id",                  :integer
    t.column "approved",                       :boolean
    t.column "terms_and_conditions",           :boolean,  :default => false
    t.column "terms_and_conditions_timestamp", :datetime
    t.column "paid",                           :boolean,  :default => true
  end

  create_table "ct_session_category_restrictions", :force => true do |t|
    t.column "category_id",   :integer
    t.column "ct_session_id", :integer
  end

  create_table "ct_session_schedules", :force => true do |t|
    t.column "ct_session_id",        :integer
    t.column "session_start_date",   :datetime
    t.column "session_end_date",     :datetime
    t.column "meet_monday",          :boolean,  :default => false
    t.column "meet_tuesday",         :boolean,  :default => false
    t.column "meet_wednesday",       :boolean,  :default => false
    t.column "meet_thursday",        :boolean,  :default => false
    t.column "meet_friday",          :boolean,  :default => false
    t.column "meet_saturday",        :boolean,  :default => false
    t.column "meet_sunday",          :boolean,  :default => false
    t.column "monday_start_time",    :time,     :default => '2000-01-01 00:00:00'
    t.column "monday_end_time",      :time,     :default => '2000-01-01 23:59:59'
    t.column "tuesday_start_time",   :time,     :default => '2000-01-01 00:00:00'
    t.column "tuesday_end_time",     :time,     :default => '2000-01-01 23:59:59'
    t.column "wednesday_start_time", :time,     :default => '2000-01-01 00:00:00'
    t.column "wednesday_end_time",   :time,     :default => '2000-01-01 23:59:59'
    t.column "thursday_start_time",  :time,     :default => '2000-01-01 00:00:00'
    t.column "thursday_end_time",    :time,     :default => '2000-01-01 23:59:59'
    t.column "friday_start_time",    :time,     :default => '2000-01-01 00:00:00'
    t.column "friday_end_time",      :time,     :default => '2000-01-01 23:59:59'
    t.column "saturday_start_time",  :time,     :default => '2000-01-01 00:00:00'
    t.column "saturday_end_time",    :time,     :default => '2000-01-01 23:59:59'
    t.column "sunday_start_time",    :time,     :default => '2000-01-01 00:00:00'
    t.column "sunday_end_time",      :time,     :default => '2000-01-01 23:59:59'
    t.column "playing_area_id",      :integer
  end

  create_table "ct_sessions", :force => true do |t|
    t.column "ct_class_id",           :integer
    t.column "s_class_name",          :string
    t.column "s_abbreviation",        :string
    t.column "s_all_bundle",          :boolean
    t.column "s_registration_start",  :datetime
    t.column "s_registration_end",    :datetime
    t.column "s_roster_maximum",      :integer,                                :default => 99
    t.column "s_price",               :decimal,  :precision => 8, :scale => 2, :default => 0.0
    t.column "s_late_date",           :datetime
    t.column "s_late_fee",            :decimal,  :precision => 8, :scale => 2
    t.column "s_comment",             :text
    t.column "class_track_id",        :integer
    t.column "s_early_bird_date",     :datetime
    t.column "s_early_bird_discount", :decimal,  :precision => 8, :scale => 2, :default => 0.0
    t.column "s_payment_due_date",    :datetime,                               :default => '2008-09-27 17:51:45'
    t.column "s_minimum_age",         :integer,                                :default => 1
    t.column "s_maximum_age",         :integer,                                :default => 99
    t.column "ct_instructor_id",      :integer
  end

  create_table "ct_settings", :force => true do |t|
    t.column "system_name",                         :string
    t.column "welcome_message",                     :text
    t.column "participant_limit_per_class",         :integer
    t.column "participant_overall_limit",           :integer
    t.column "verify_ct_eligibility",               :boolean,  :default => false
    t.column "master_ct_terms_and_conditions",      :boolean
    t.column "master_ct_terms_and_conditions_text", :text
    t.column "class_terms_and_conditions",          :boolean
    t.column "class_terms_and_conditions_text",     :text
    t.column "last_member_export",                  :datetime
    t.column "require_approval",                    :boolean,  :default => false
  end

  create_table "data_participant_templates", :force => true do |t|
    t.column "data_template_id", :integer
    t.column "record_length",    :integer
    t.column "member_id",        :string
    t.column "card_number",      :string
    t.column "last_name",        :string
    t.column "mi",               :string
    t.column "first_name",       :string
    t.column "title",            :string
    t.column "gender",           :string
    t.column "date_of_birth",    :string
    t.column "address_line_1",   :string
    t.column "address_line_2",   :string
    t.column "city",             :string
    t.column "state",            :string
    t.column "zip",              :string
    t.column "home_phone",       :string
    t.column "work_phone",       :string
    t.column "mobile_phone",     :string
    t.column "fax",              :string
    t.column "email_address",    :string
    t.column "emergency_name",   :string
    t.column "emergency_phone",  :string
    t.column "job_title",        :string
    t.column "mail_code",        :string
    t.column "category",         :string
    t.column "sub_category",     :string
    t.column "start_date",       :string
    t.column "end_date",         :string
    t.column "comments",         :string
    t.column "imtrack",          :string
    t.column "classtrack",       :string
  end

  create_table "data_templates", :force => true do |t|
    t.column "data_template_name", :string
    t.column "data_template_type", :string
    t.column "last_run",           :datetime
    t.column "export",             :boolean
    t.column "category_check",     :boolean
    t.column "category_id",        :integer
    t.column "created_by",         :string
  end

  create_table "desktop_users", :force => true do |t|
    t.column "user_name",     :string
    t.column "password",      :string
    t.column "last_name",     :string
    t.column "first_name",    :string
    t.column "imtrack",       :boolean
    t.column "facilitytrack", :boolean
    t.column "classtrack",    :boolean
    t.column "reftrack",      :boolean
  end

  create_table "discount_logs", :force => true do |t|
    t.column "participant_id", :integer
    t.column "comment",        :string
    t.column "amount",         :decimal, :precision => 8, :scale => 2, :default => 0.0
  end

  create_table "email_custom_texts", :force => true do |t|
    t.column "master_header",  :text
    t.column "master_footer",  :text
    t.column "receipt_header", :text
    t.column "receipt_footer", :text
  end

  create_table "emails", :force => true do |t|
    t.column "from",              :string
    t.column "to",                :string
    t.column "last_send_attempt", :integer,  :default => 0
    t.column "mail",              :text
    t.column "created_on",        :datetime
  end

  create_table "facilities", :force => true do |t|
    t.column "facility_name",         :string
    t.column "supervisor_name",       :string
    t.column "supervisor_phone",      :string
    t.column "supervisor_email",      :string
    t.column "address_1",             :string
    t.column "address_2",             :string
    t.column "city",                  :string
    t.column "state",                 :string
    t.column "zip",                   :string
    t.column "facility_abbreviation", :string
    t.column "pool",                  :boolean
    t.column "number_of_lanes",       :integer
    t.column "default_length",        :integer
    t.column "default_unit",          :integer
    t.column "time_frame_range",      :integer
    t.column "added_by",              :string
  end

  create_table "facility_events", :force => true do |t|
    t.column "im_game_id",        :integer
    t.column "ft_reservation_id", :integer
    t.column "ct_reservation_id", :integer
  end

  create_table "facility_time_frames", :force => true do |t|
    t.column "facility_id", :integer
    t.column "day_number",  :integer
    t.column "start_time",  :datetime
    t.column "end_time",    :datetime
    t.column "off_peak",    :boolean
  end

  create_table "fee_logs", :force => true do |t|
    t.column "participant_id", :integer
    t.column "comment",        :string
    t.column "amount",         :decimal, :precision => 8, :scale => 2, :default => 0.0
  end

  create_table "ft_reservation_recurrence_dates", :force => true do |t|
    t.column "reservation_recurrence_id", :integer
    t.column "recurrence_date",           :datetime
    t.column "recurrence_type",           :integer
  end

  create_table "ft_reservation_recurrences", :force => true do |t|
    t.column "reservation_id",    :integer
    t.column "start_time",        :datetime
    t.column "end_time",          :datetime
    t.column "pattern_selection", :integer
    t.column "flag_1",            :string
    t.column "flag_2",            :string
    t.column "flag_3",            :string
    t.column "flag_4",            :string
    t.column "flag_5",            :string
    t.column "flag_6",            :string
    t.column "flag_7",            :string
    t.column "flag_8",            :string
    t.column "start_date",        :datetime
    t.column "end_selection",     :integer
    t.column "end_flag",          :string
  end

  create_table "ft_reservations", :force => true do |t|
    t.column "playing_area_id",            :integer
    t.column "participant_id",             :integer
    t.column "start_date_time",            :datetime
    t.column "end_date_time",              :datetime
    t.column "all_day",                    :boolean
    t.column "description",                :text
    t.column "ft_facility_contract_id",    :integer
    t.column "price",                      :decimal,  :precision => 8, :scale => 2
    t.column "paid",                       :boolean
    t.column "receipt_number",             :integer
    t.column "purchase_number",            :integer
    t.column "whole_facility",             :boolean
    t.column "reservation_recurrence_id",  :integer
    t.column "recurrence_sequence_number", :integer
    t.column "added_by",                   :string
  end

  create_table "holds", :force => true do |t|
    t.column "active",         :boolean
    t.column "participant_id", :integer
    t.column "option_1",       :string
    t.column "option_2",       :string
    t.column "option_3",       :string
    t.column "option_4",       :string
    t.column "option_5",       :string
    t.column "option_6",       :string
    t.column "duration",       :integer
    t.column "start_date",     :datetime
    t.column "end_date",       :datetime
    t.column "total_count",    :integer
    t.column "count_left",     :integer
    t.column "description",    :text
    t.column "added_by",       :string
  end

  create_table "im_brackets", :force => true do |t|
    t.column "im_sport_id",          :integer
    t.column "bracket_name",         :string
    t.column "bracket_abbreviation", :string
    t.column "im_league_id",         :integer
    t.column "number_of_teams",      :integer
    t.column "double_elimination",   :boolean
    t.column "losers_side",          :boolean
  end

  create_table "im_captain_cards", :force => true do |t|
    t.column "password",       :text
    t.column "participant_id", :integer
  end

  create_table "im_colors", :force => true do |t|
    t.column "color_name", :string
    t.column "hex",        :string
  end

  create_table "im_column_header_codes", :force => true do |t|
    t.column "header_name",  :string
    t.column "display_name", :string
    t.column "column_name",  :string
    t.column "alignment",    :string
    t.column "link_to_team", :boolean, :default => false
  end

  create_table "im_column_headers", :force => true do |t|
    t.column "im_sport_id",              :integer
    t.column "header_name",              :string
    t.column "index",                    :integer
    t.column "im_column_header_code_id", :integer
  end

  create_table "im_day_of_plays", :force => true do |t|
    t.column "im_sport_id", :integer
    t.column "dop_name",    :string
    t.column "imtrack_id",  :integer
    t.column "game_sets",   :integer
    t.column "frequency",   :integer
    t.column "sunday",      :boolean
    t.column "monday",      :boolean
    t.column "tuesday",     :boolean
    t.column "wednesday",   :boolean
    t.column "thursday",    :boolean
    t.column "friday",      :boolean
    t.column "saturday",    :boolean
    t.column "start_date",  :datetime
  end

  create_table "im_desktop_user_options", :force => true do |t|
    t.column "desktop_user_id",        :integer
    t.column "change",                 :boolean
    t.column "add_area",               :boolean
    t.column "add_facility",           :boolean
    t.column "add_sport",              :boolean
    t.column "add_term",               :boolean
    t.column "add_user",               :boolean
    t.column "admin",                  :boolean
    t.column "change_password",        :boolean
    t.column "color_scheme",           :boolean
    t.column "database",               :boolean
    t.column "delete_area",            :boolean
    t.column "delete_facility",        :boolean
    t.column "delete_sport",           :boolean
    t.column "delete_term",            :boolean
    t.column "delete_user",            :boolean
    t.column "edit_area",              :boolean
    t.column "edit_facility",          :boolean
    t.column "edit_sport",             :boolean
    t.column "edit_term",              :boolean
    t.column "edit_user",              :boolean
    t.column "frames_setup",           :boolean
    t.column "maintenance",            :boolean
    t.column "options",                :boolean
    t.column "security",               :boolean
    t.column "serial_numbers",         :boolean
    t.column "view_calendar",          :boolean
    t.column "web_settings",           :boolean
    t.column "add_division",           :boolean
    t.column "add_league_score",       :boolean
    t.column "delete_division",        :boolean
    t.column "delete_league_score",    :boolean
    t.column "edit_division",          :boolean
    t.column "edit_league_score",      :boolean
    t.column "league_play",            :boolean
    t.column "add_bracket",            :boolean
    t.column "add_bracket_score",      :boolean
    t.column "delete_bracket",         :boolean
    t.column "delete_bracket_score",   :boolean
    t.column "edit_bracket",           :boolean
    t.column "edit_bracket_score",     :boolean
    t.column "bracket_play",           :boolean
    t.column "add_participant",        :boolean
    t.column "add_roster",             :boolean
    t.column "change_eligibility",     :boolean
    t.column "delete_participant",     :boolean
    t.column "delete_roster",          :boolean
    t.column "edit_participant",       :boolean
    t.column "participant",            :boolean
    t.column "participant_search",     :boolean
    t.column "add_client_area",        :boolean
    t.column "add_dop",                :boolean
    t.column "add_client_facility",    :boolean
    t.column "add_league",             :boolean
    t.column "delete_client_area",     :boolean
    t.column "delete_dop",             :boolean
    t.column "edit_client_facility",   :boolean
    t.column "edit_league",            :boolean
    t.column "client_maintenance",     :boolean
    t.column "new_season",             :boolean
    t.column "view_client_calendar",   :boolean
    t.column "client_color_scheme",    :boolean
    t.column "printing",               :boolean
    t.column "view_pages",             :boolean
    t.column "client_web_pages",       :boolean
    t.column "delete_client_facility", :boolean
    t.column "delete_league",          :boolean
    t.column "edit_client_area",       :boolean
    t.column "edit_dop",               :boolean
  end

  create_table "im_divisions", :force => true do |t|
    t.column "im_league_id",       :integer
    t.column "im_day_of_play_id",  :integer
    t.column "division_name",      :string
    t.column "number_of_teams",    :integer
    t.column "start_time",         :time
    t.column "end_time",           :time
    t.column "rotating",           :boolean
    t.column "imtrack_id",         :integer
    t.column "game_played",        :boolean, :default => false
    t.column "game_sets",          :integer
    t.column "game_length_hour",   :integer
    t.column "game_length_minute", :integer
    t.column "scheduled",          :boolean
    t.column "schedule_type",      :integer
    t.column "setting",            :integer
    t.column "manual_sort",        :boolean
  end

  create_table "im_dop_dates", :force => true do |t|
    t.column "im_day_of_play_id", :integer
    t.column "date",              :datetime
    t.column "index",             :integer
  end

  create_table "im_excel_controls", :force => true do |t|
    t.column "control_name",     :string
    t.column "control_type",     :string
    t.column "file_name",        :string
    t.column "sport_cell",       :string
    t.column "date_cell",        :string
    t.column "time_cell",        :string
    t.column "field_cell",       :string
    t.column "division_cell",    :string
    t.column "league_cell",      :string
    t.column "home_team_cell",   :string
    t.column "home_color_cell",  :string
    t.column "away_team_cell",   :string
    t.column "away_color_cell",  :string
    t.column "home_id_cell",     :string
    t.column "home_roster_cell", :string
    t.column "away_id_cell",     :string
    t.column "away_roster_cell", :string
    t.column "line_space",       :integer
    t.column "roster_spots",     :integer
    t.column "header_cell",      :string
    t.column "column_factor",    :integer
    t.column "row_factor",       :integer
    t.column "worksheet_number", :integer
  end

  create_table "im_free_agent_invitations", :force => true do |t|
    t.column "im_free_agent_id", :integer
    t.column "im_team_id",       :integer
    t.column "declined",         :boolean, :default => false
    t.column "accepted",         :boolean, :default => false
  end

  create_table "im_free_agents", :force => true do |t|
    t.column "participant_id", :integer
    t.column "im_league_id",   :integer
    t.column "im_division_id", :integer
    t.column "comment",        :text
  end

  create_table "im_game_of_the_days", :force => true do |t|
    t.column "im_sport_id",         :integer
    t.column "game_date",           :datetime
    t.column "im_game_id",          :integer
    t.column "previous_im_game_id", :integer
    t.column "global",              :boolean
    t.column "header",              :string
    t.column "coments",             :text
    t.column "show_previous",       :boolean
  end

  create_table "im_games", :force => true do |t|
    t.column "parent_id",              :integer,                               :default => 0
    t.column "game_set",               :integer
    t.column "game_number",            :integer
    t.column "match_up",               :string
    t.column "im_league_id",           :integer
    t.column "home_team_id",           :integer
    t.column "away_team_id",           :integer
    t.column "home_seed",              :integer
    t.column "away_seed",              :integer
    t.column "game_time",              :date
    t.column "start_time",             :time
    t.column "end_time",               :time
    t.column "playing_area_id",        :integer
    t.column "played",                 :boolean,                               :default => false
    t.column "home_score",             :integer
    t.column "away_score",             :integer
    t.column "number_of_sets",         :integer
    t.column "home_set_1",             :integer
    t.column "away_set_1",             :integer
    t.column "home_set_2",             :integer
    t.column "away_set_2",             :integer
    t.column "home_set_3",             :integer
    t.column "away_set_3",             :integer
    t.column "home_set_4",             :integer
    t.column "away_set_4",             :integer
    t.column "home_set_5",             :integer
    t.column "away_set_5",             :integer
    t.column "home_sportsmanship",     :decimal, :precision => 5, :scale => 2
    t.column "away_sportsmanship",     :decimal, :precision => 5, :scale => 2
    t.column "result",                 :string
    t.column "playoff",                :boolean,                               :default => false
    t.column "home_high",              :boolean,                               :default => false
    t.column "next_playoff_game_id",   :string
    t.column "next_playoff_game_l_id", :string
    t.column "comment",                :text
    t.column "im_bracket_id",          :integer
    t.column "reservation_id",         :integer
    t.column "added_by",               :string
  end

  create_table "im_leagues", :force => true do |t|
    t.column "im_sport_id", :integer
    t.column "parent_id",   :integer, :default => 0
    t.column "league_name", :string
    t.column "max_allowed", :integer, :default => 0
    t.column "comment",     :text
    t.column "imtrack_id",  :integer
  end

  create_table "im_options", :force => true do |t|
    t.column "option", :string
    t.column "flag",   :string
  end

  create_table "im_payment_options", :force => true do |t|
    t.column "payment_option",         :string
    t.column "team_payment_selection", :string
  end

  create_table "im_product_informations", :force => true do |t|
    t.column "customer_id",           :string
    t.column "customer_name",         :string
    t.column "master_serial_number",  :string
    t.column "evaluation_start_date", :string
    t.column "evaluation_stop_date",  :string
  end

  create_table "im_ranking_breakdowns", :force => true do |t|
    t.column "im_ranking_id", :integer
    t.column "equals",        :boolean
    t.column "miniimum",      :string
    t.column "maximum",       :string
    t.column "bonus",         :integer
  end

  create_table "im_rankings", :force => true do |t|
    t.column "breakdown",   :string
    t.column "offense",     :boolean
    t.column "im_sport_id", :integer
  end

  create_table "im_roster_term_and_conditions", :force => true do |t|
    t.column "im_sport_id",          :integer
    t.column "terms_and_conditions", :text
  end

  create_table "im_rosters", :force => true do |t|
    t.column "im_team_id",                     :integer
    t.column "participant_id",                 :integer
    t.column "captain",                        :boolean
    t.column "im_track_id",                    :integer
    t.column "terms_and_conditions",           :boolean,  :default => false
    t.column "terms_and_conditions_timestamp", :datetime
    t.column "paid",                           :boolean,  :default => true
  end

  create_table "im_serial_numbers", :force => true do |t|
    t.column "serial_number", :integer
    t.column "installed",     :boolean
    t.column "logged_in",     :boolean
    t.column "im_user_id",    :integer
  end

  create_table "im_settings", :force => true do |t|
    t.column "system_name",                         :string
    t.column "welcome_message",                     :text
    t.column "participant_roster_limit_per_sport",  :integer
    t.column "participant_roster_limit_per_league", :integer
    t.column "overall_captain_limit",               :integer
    t.column "captain_limit_per_sport",             :integer
    t.column "captain_limit_per_league",            :integer
    t.column "captain_limit_per_division",          :integer
    t.column "verify_im_eligibility",               :boolean
    t.column "captain_cards",                       :boolean
    t.column "free_agents",                         :boolean
    t.column "allow_multiple_colors",               :boolean
    t.column "master_im_terms_and_conditions",      :boolean
    t.column "master_im_terms_and_conditions_text", :text
    t.column "team_terms_and_conditions",           :boolean
    t.column "team_terms_and_conditions_text",      :text
    t.column "roster_terms_and_conditions",         :boolean
    t.column "roster_terms_and_conditions_text",    :text
    t.column "last_member_export",                  :datetime
    t.column "default_page",                        :string
    t.column "im_payment_option_id",                :integer,  :default => 1
    t.column "require_approval",                    :boolean,  :default => false
  end

  create_table "im_sports", :force => true do |t|
    t.column "term_id",               :integer
    t.column "sport_name",            :string
    t.column "start_date",            :datetime
    t.column "end_date",              :datetime
    t.column "roster_end_date",       :datetime
    t.column "jersey_color",          :boolean
    t.column "price",                 :decimal,  :precision => 8, :scale => 2, :default => 0.0
    t.column "roster_minimum",        :integer,                                :default => 1
    t.column "roster_maximum",        :integer,                                :default => 99
    t.column "imtrack_id",            :integer
    t.column "exported",              :boolean,                                :default => false
    t.column "roster_price",          :decimal,  :precision => 8, :scale => 2, :default => 0.0
    t.column "individual_sport",      :boolean,                                :default => false
    t.column "default_hour",          :integer,                                :default => 1
    t.column "default_minute",        :integer,                                :default => 0
    t.column "payment_due_date",      :datetime,                               :default => '2008-09-27 17:51:46'
    t.column "sport_model",           :string
    t.column "scoring_model",         :integer
    t.column "sportsmanship",         :boolean
    t.column "minimum_sportsmanship", :decimal,  :precision => 8, :scale => 2
    t.column "no_show_limit",         :boolean
    t.column "no_show_count",         :integer
    t.column "participants",          :boolean
    t.column "statistics",            :boolean
    t.column "show_rankings",         :boolean
    t.column "print_rankings",        :boolean
    t.column "sort_heading_1",        :string
    t.column "sorting_1",             :integer
    t.column "sort_heading_2",        :string
    t.column "sorting_2",             :integer
    t.column "sort_heading_3",        :string
    t.column "sorting_3",             :integer
    t.column "statistics_table",      :string
    t.column "gamesheet_control_id",  :integer
    t.column "scorecard_control_id",  :integer
    t.column "last_accessed",         :datetime
    t.column "last_web_creation",     :datetime
    t.column "create_sport_pages",    :boolean
    t.column "sport_link",            :boolean
    t.column "bracket_link",          :boolean
    t.column "daily_link",            :boolean
    t.column "god_link",              :boolean
    t.column "league_link",           :boolean
    t.column "top_ten_link",          :boolean
    t.column "stat_top_link",         :boolean
    t.column "stat_all_link",         :boolean
    t.column "welcome_message",       :text
  end

  create_table "im_statistics", :force => true do |t|
    t.column "im_sport_id", :integer
    t.column "stat_name",   :string
    t.column "formula",     :string
    t.column "column_name", :string
    t.column "print",       :boolean
    t.column "sort",        :string
    t.column "other",       :string
  end

  create_table "im_team_term_and_conditions", :force => true do |t|
    t.column "im_sport_id",          :integer
    t.column "terms_and_conditions", :text
  end

  create_table "im_teams", :force => true do |t|
    t.column "im_division_id",                 :integer
    t.column "im_league_id",                   :integer
    t.column "team_name",                      :string
    t.column "team_number",                    :integer
    t.column "im_color_id",                    :integer
    t.column "approved",                       :boolean
    t.column "password",                       :string
    t.column "comment",                        :text
    t.column "imtrack_id",                     :integer
    t.column "terms_and_conditions",           :boolean,                                :default => false
    t.column "terms_and_conditions_timestamp", :datetime
    t.column "paid",                           :boolean,                                :default => true
    t.column "charge_roster",                  :boolean,                                :default => false
    t.column "playing_area_id",                :integer
    t.column "default_team",                   :boolean,                                :default => false
    t.column "games",                          :integer
    t.column "wins",                           :integer
    t.column "losses",                         :integer
    t.column "ties",                           :integer
    t.column "forfiets",                       :integer
    t.column "no_shows",                       :integer
    t.column "winning_percentage",             :decimal,  :precision => 8, :scale => 2
    t.column "percentage_bonus",               :integer
    t.column "win_bonus",                      :integer
    t.column "offense",                        :integer
    t.column "offense_bonus",                  :integer
    t.column "defense",                        :integer
    t.column "defense_bonus",                  :integer
    t.column "sportsmanship",                  :decimal,  :precision => 8, :scale => 2
    t.column "sportsmanship_average",          :decimal,  :precision => 8, :scale => 2
    t.column "sportsmanship_bonus",            :integer
    t.column "points_allowed",                 :integer
    t.column "points_allowed_bonus",           :integer
    t.column "points_scored",                  :integer
    t.column "points_scored_bonus",            :integer
    t.column "misc_bonus",                     :integer
    t.column "rating",                         :decimal,  :precision => 8, :scale => 2
    t.column "rating_average",                 :decimal,  :precision => 8, :scale => 2
    t.column "ranking",                        :integer
    t.column "points",                         :integer
    t.column "place",                          :integer
  end

  create_table "im_web_setting_colors", :force => true do |t|
    t.column "im_sport_id",          :integer
    t.column "master",               :boolean
    t.column "active_link",          :string
    t.column "bracket_background",   :string
    t.column "bracket_font",         :string
    t.column "bracket_main_font",    :string
    t.column "bracket_shadow",       :string
    t.column "hyperlink",            :string
    t.column "standings_background", :string
    t.column "standings_dark",       :string
    t.column "standings_dark_font",  :string
    t.column "standings_font",       :string
    t.column "standings_light",      :string
    t.column "standings_light_font", :string
    t.column "visited_link",         :string
  end

  create_table "im_web_setting_mains", :force => true do |t|
    t.column "contact_name",       :string
    t.column "email_address",      :string
    t.column "home_page",          :string
    t.column "company_name",       :string
    t.column "sort",               :integer
    t.column "first_logo",         :string
    t.column "second_logo",        :string
    t.column "hyperlink_one",      :string
    t.column "hyperlink_two",      :string
    t.column "banner_background",  :string
    t.column "banner_font",        :string
    t.column "content_background", :string
    t.column "content_font",       :string
    t.column "content_hyperlink",  :string
    t.column "message",            :text
  end

  create_table "im_web_setting_securities", :force => true do |t|
    t.column "ftp_option",            :integer
    t.column "host_name",             :string
    t.column "ssl",                   :boolean
    t.column "login_name",            :string
    t.column "login_password",        :string
    t.column "upload_directory",      :string
    t.column "page_directory",        :string
    t.column "external_program",      :string
    t.column "command_line_argument", :string
  end

  create_table "line_items", :force => true do |t|
    t.column "participant_id",        :integer,                                                                   :null => false
    t.column "order_id",              :integer
    t.column "payment_item_id",       :integer,                                                                   :null => false
    t.column "im_team_id",            :integer
    t.column "im_roster_id",          :integer
    t.column "ct_roster_id",          :integer
    t.column "price",                 :decimal,  :precision => 8, :scale => 2,                                    :null => false
    t.column "discount_log_id",       :integer
    t.column "created_at",            :datetime
    t.column "comment",               :string
    t.column "payment_due_date",      :datetime,                               :default => '2011-11-29 02:38:25'
    t.column "fee_log_id",            :integer
    t.column "google_receipt_number", :string
  end

  create_table "master_settings", :force => true do |t|
    t.column "master_terms_and_conditions",      :boolean
    t.column "master_terms_and_conditions_text", :text
    t.column "verify_participants",              :boolean,                               :default => false
    t.column "require_phone_number",             :boolean,                               :default => true
    t.column "require_address",                  :boolean,                               :default => true
    t.column "system_name",                      :string,                                :default => "Facilitrax by Recreational Solutions"
    t.column "welcome_message",                  :text
    t.column "customer_id",                      :string,                                :default => "test"
    t.column "require_member_number",            :boolean,                               :default => false
    t.column "default_payment_due_setting",      :boolean,                               :default => false
    t.column "default_payment_due_days",         :integer,                               :default => 2
    t.column "require_DOB",                      :boolean,                               :default => false
    t.column "require_category",                 :boolean,                               :default => false
    t.column "return_url",                       :string,                                :default => "localhost:3000"
    t.column "require_membership_fee",           :boolean,                               :default => false
    t.column "membership_fee",                   :decimal, :precision => 8, :scale => 2, :default => 0.0
    t.column "application_fee",                  :decimal, :precision => 8, :scale => 2, :default => 0.0
    t.column "logout_link",                      :string
    t.column "database_version",                 :integer,                               :default => 0
    t.column "auto_delete_past_due_items",       :boolean,                               :default => false
  end

  create_table "options", :force => true do |t|
    t.column "option", :string
    t.column "flag",   :string
  end

  create_table "orders", :force => true do |t|
    t.column "payment_type_id", :integer
    t.column "created_at",      :datetime
    t.column "participant_id",  :integer
    t.column "completed",       :boolean,  :default => false
  end

  create_table "participant_contracts", :force => true do |t|
    t.column "contract_name",     :string
    t.column "date_type",         :integer
    t.column "start_date",        :datetime
    t.column "end_date",          :datetime
    t.column "length",            :integer
    t.column "length_unit",       :integer
    t.column "block_pass",        :boolean
    t.column "number_of_entries", :integer
    t.column "day_time_access",   :boolean
    t.column "time_range",        :integer
    t.column "day",               :integer
    t.column "start_time",        :datetime
    t.column "end_time",          :datetime
    t.column "off_peak",          :boolean
  end

  create_table "participant_custom_field_entries", :force => true do |t|
    t.column "participant_id",              :integer
    t.column "participant_custom_field_id", :integer
    t.column "field_data",                  :string
  end

  create_table "participant_custom_fields", :force => true do |t|
    t.column "field_name",  :string
    t.column "required",    :boolean, :default => false
    t.column "inheritable", :boolean, :default => false
  end

  create_table "participant_events", :force => true do |t|
    t.column "participant_id",    :integer
    t.column "ct_reservation_id", :integer
  end

  create_table "participant_form_orders", :force => true do |t|
    t.column "participant_column_human_name", :string
    t.column "participant_column_name",       :string
    t.column "participant_column_required",   :boolean
    t.column "participant_custom_field_id",   :integer
    t.column "sort_number",                   :integer
    t.column "show_field",                    :boolean, :default => true
    t.column "participant_column_type",       :string,  :default => "text"
    t.column "show_on_reports",               :boolean, :default => true
  end

  create_table "participant_memberships", :force => true do |t|
    t.column "participant_id",          :integer
    t.column "participant_contract_id", :integer
    t.column "start_date_time",         :datetime
    t.column "end_date_time",           :datetime
    t.column "number_of_entries",       :integer
    t.column "entries_remaining",       :integer
    t.column "paid",                    :boolean
    t.column "receipt_number",          :integer
  end

  create_table "participant_titles", :force => true do |t|
    t.column "title", :string
  end

  create_table "participants", :force => true do |t|
    t.column "member_id",                         :string
    t.column "first_name",                        :string
    t.column "last_name",                         :string
    t.column "mi",                                :string
    t.column "phone",                             :string
    t.column "email",                             :string
    t.column "address_line_1",                    :string
    t.column "address_line_2",                    :string
    t.column "city",                              :string
    t.column "state",                             :string
    t.column "zip",                               :string
    t.column "im_active",                         :boolean,  :default => false
    t.column "imtrack_id",                        :integer
    t.column "im_terms_and_conditions",           :boolean,  :default => false
    t.column "terms_and_conditions",              :boolean,  :default => false
    t.column "ct_terms_and_conditions",           :boolean,  :default => false
    t.column "ct_active",                         :boolean,  :default => false
    t.column "updated_at",                        :datetime
    t.column "im_terms_and_conditions_timestamp", :datetime
    t.column "terms_and_conditions_timestamp",    :datetime
    t.column "ct_terms_and_conditions_timestamp", :datetime
    t.column "rt_terms_and_conditions",           :boolean,  :default => false
    t.column "rt_active",                         :boolean,  :default => false
    t.column "date_of_birth",                     :date
    t.column "category_id",                       :integer
    t.column "gender",                            :boolean,  :default => true
    t.column "parent_id",                         :integer,  :default => 0
    t.column "card_number",                       :string
    t.column "participant_title_id",              :integer
    t.column "work_phone",                        :string
    t.column "mobile_phone",                      :string
    t.column "fax",                               :string
    t.column "emergency_name",                    :string
    t.column "emergency_phone",                   :string
    t.column "job_title",                         :string
    t.column "mail_code",                         :string
    t.column "comments",                          :text
    t.column "contract_unit",                     :string
    t.column "contract_length",                   :string
    t.column "start_date",                        :datetime
    t.column "end_date",                          :datetime
    t.column "head_of_household",                 :boolean
    t.column "added_by",                          :string
    t.column "organization",                      :boolean
    t.column "allow_members",                     :boolean
    t.column "organization_category_id",          :integer
    t.column "modified_date",                     :datetime
    t.column "paid_membership_fee",               :boolean,  :default => false
    t.column "paid_application_fee",              :boolean,  :default => false
    t.column "yeah_code",                         :string
  end

  create_table "payment_items", :force => true do |t|
    t.column "payment_item", :string
    t.column "table_name",   :string
  end

  create_table "payment_settings", :force => true do |t|
    t.column "paypal",                          :boolean
    t.column "paypal_api_user_name",            :string
    t.column "paypal_api_password",             :string
    t.column "paypal_api_signature",            :string
    t.column "cfm_authorization",               :boolean, :default => false
    t.column "authorize_net",                   :boolean
    t.column "authorize_net_login",             :string
    t.column "authorize_net_transaction_key",   :string
    t.column "receive_payment_notifications",   :boolean
    t.column "payment_notification_email",      :string
    t.column "nelix",                           :boolean, :default => false
    t.column "nelix_user_name",                 :string
    t.column "cfm_authorization_authorize_net", :boolean, :default => false
    t.column "cfm_authorization_nelix",         :boolean, :default => false
    t.column "cfm_authorization_paypal",        :boolean, :default => false
  end

  create_table "payment_types", :force => true do |t|
    t.column "payment_type", :string
    t.column "admin_pay",    :boolean
  end

  create_table "playing_areas", :force => true do |t|
    t.column "facility_id",       :integer
    t.column "playing_area_name", :string
    t.column "area_abbreviation", :string
    t.column "parent_id",         :integer, :default => 0
    t.column "allow_consecutive", :boolean
    t.column "allow_multiple",    :boolean
    t.column "approval",          :boolean
    t.column "check_in",          :boolean
    t.column "alarm",             :boolean
    t.column "added_by",          :string
    t.column "sub_area",          :boolean
  end

  create_table "rt_employee_calendars", :force => true do |t|
    t.column "participant_id",             :integer
    t.column "rt_participant_out_date_id", :integer
    t.column "rt_employee_schedule_id",    :integer
    t.column "rt_employee_turnback_id",    :integer
  end

  create_table "rt_employee_schedules", :force => true do |t|
    t.column "participant_id",       :integer
    t.column "im_game_id",           :integer
    t.column "rt_employee_title_id", :integer
    t.column "status",               :integer, :default => 0
  end

  create_table "rt_employee_title_league_relationships", :force => true do |t|
    t.column "rt_employee_title_id", :integer
    t.column "im_league_id",         :integer
    t.column "rt_user_group_id",     :integer, :default => 0
  end

  create_table "rt_employee_titles", :force => true do |t|
    t.column "im_sport_id",      :integer
    t.column "employee_title",   :string
    t.column "abbreviation",     :string
    t.column "sorting_order",    :integer, :default => 0
    t.column "make_a_default",   :boolean, :default => true
    t.column "rt_user_group_id", :integer
  end

  create_table "rt_employee_turnbacks", :force => true do |t|
    t.column "participant_id", :integer
    t.column "im_game_id",     :integer
  end

  create_table "rt_join_requests", :force => true do |t|
    t.column "participant_id", :integer
    t.column "comment",        :text
    t.column "declined",       :boolean,  :default => false
    t.column "created_at",     :datetime
  end

  create_table "rt_memo_user_group_relationships", :force => true do |t|
    t.column "rt_user_group_id", :integer
    t.column "rt_memo_id",       :integer
  end

  create_table "rt_memos", :force => true do |t|
    t.column "memo_title", :string
    t.column "summary",    :text
    t.column "active",     :boolean, :default => true
    t.column "created_on", :date
    t.column "memo_file",  :string
  end

  create_table "rt_participant_facility_blocks", :force => true do |t|
    t.column "participant_id", :integer
    t.column "facility_id",    :integer
  end

  create_table "rt_participant_out_dates", :force => true do |t|
    t.column "participant_id", :integer
    t.column "parent_id",      :integer, :default => 0
    t.column "out_date",       :date,    :default => '2008-09-27'
    t.column "start_time",     :time,    :default => '2000-01-01 00:00:00'
    t.column "end_time",       :time,    :default => '2000-01-01 23:55:00'
    t.column "comment",        :text
    t.column "end_date",       :date
  end

  create_table "rt_participant_team_blocks", :force => true do |t|
    t.column "participant_id", :integer
    t.column "im_team_id",     :integer
  end

  create_table "rt_participant_team_relationships", :force => true do |t|
    t.column "participant_id",   :integer
    t.column "im_team_id",       :integer
    t.column "rt_user_group_id", :integer
  end

  create_table "rt_participant_user_group_relationships", :force => true do |t|
    t.column "rt_user_group_id", :integer
    t.column "participant_id",   :integer
  end

  create_table "rt_settings", :force => true do |t|
    t.column "system_name",                         :string
    t.column "welcome_message",                     :text
    t.column "last_schedule_date",                  :date
    t.column "default_start_time",                  :time
    t.column "scheduling_request_method",           :boolean
    t.column "show_directions",                     :boolean
    t.column "system_admin_name",                   :string
    t.column "system_admin_email",                  :string
    t.column "master_rt_terms_and_conditions",      :boolean
    t.column "master_rt_terms_and_conditions_text", :text
    t.column "allow_team_blocks",                   :boolean, :default => false
    t.column "allow_facility_blocks",               :boolean, :default => false
    t.column "send_game_notification_emails",       :boolean, :default => false
    t.column "require_game_acceptance",             :boolean, :default => false
    t.column "automatically_publish_assignments",   :boolean, :default => false
  end

  create_table "rt_user_group_sport_relationships", :force => true do |t|
    t.column "rt_user_group_id", :integer
    t.column "im_sport_id",      :integer
  end

  create_table "rt_user_group_types", :force => true do |t|
    t.column "user_group_type", :string
    t.column "description",     :string
  end

  create_table "rt_user_groups", :force => true do |t|
    t.column "user_group_name",             :string
    t.column "rt_user_group_type_id",       :integer
    t.column "non_employee_view_officials", :boolean, :default => false
    t.column "non_employee_schedule_games", :boolean, :default => false
    t.column "power_view_all_sports",       :boolean, :default => false
    t.column "allow_request",               :boolean
    t.column "internal",                    :boolean, :default => false
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "terms", :force => true do |t|
    t.column "term_name",                         :string
    t.column "imtrack_id",                        :integer
    t.column "default_class_registration_start",  :datetime
    t.column "default_class_registration_end",    :datetime
    t.column "default_class_price",               :decimal,  :precision => 8, :scale => 2, :default => 0.0
    t.column "default_class_roster_maximum",      :integer,                                :default => 99
    t.column "default_class_late_date",           :datetime
    t.column "default_class_late_price",          :decimal,  :precision => 8, :scale => 2, :default => 0.0
    t.column "default_class_early_bird_date",     :datetime
    t.column "default_class_early_bird_discount", :decimal,  :precision => 8, :scale => 2, :default => 0.0
    t.column "default_class_payment_due_date",    :datetime
    t.column "default_team_payment_due_date",     :datetime
    t.column "default_class_minimum_age",         :integer,                                :default => 1
    t.column "default_class_maximum_age",         :integer,                                :default => 99
  end

  create_table "users", :force => true do |t|
    t.column "participant_id",            :integer
    t.column "login",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "admin",                     :boolean
    t.column "reset_password",            :string
  end

end
